version: "3.9"

services:
  # PostgreSQL: stores document metadata, tags, ACLs
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms123
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    healthcheck:
      # NOTE: it's pg_isready (underscore), not pg-isready
      test: ["CMD-SHELL", "pg_isready -U dms"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO: S3-compatible object storage for files
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"   # S3 API endpoint
      - "9001:9001"   # Web console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # OpenSearch: full-text search engine
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      discovery.type: single-node            # 1-node dev cluster
      plugins.security.disabled: "true"      # disable security for local dev
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"                          # REST API
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Keycloak: identity provider (users/roles, issues JWTs)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5